### ISSUE TITLE
Players can use all fireworks before game starts

### ISSUE THREAD

**Issue by Gegy** [NucleoidMC/loop-de-loop#10]

**Comment by Restioson** [comment]
That seems like a bad idea

**Comment by Gegy** [comment]
The issue is that they can- but they should not be able to

**Comment by Restioson** [comment]
I meant it's a bad idea for them to that :p smh just don't

Seriously, should be a trivial fix (just to cancel the interact on firework when frozen)

**Comment by Restioson** [comment]
I'm not considering this a bug since while you can do it, it doesn't softlock you or anything, it's just a bad decision with an appropriate reponse. Any objections to leaving the game as it is?
